// This file is generated by Slice Machine. Update with care!

import HeaderHome from './HeaderHome';
import HeaderStandard from './HeaderStandard';
import ImgCarousel from './ImgCarousel';
import Service from './Service';
import TeamMember from './TeamMember';
import VerticalListSmall from './VerticalListSmall';

export {
	HeaderHome,
	HeaderStandard,
	ImgCarousel,
	Service,
	TeamMember,
	VerticalListSmall,
};

export const components = {
	header_home: HeaderHome,
	header_standard: HeaderStandard,
	img_carousel: ImgCarousel,
	service: Service,
	team_member: TeamMember,
	vertical_list_small: VerticalListSmall,
};
