// This file is generated by Slice Machine. Update with care!

import HeaderHome from './HeaderHome';
import HeaderStandard from './HeaderStandard';
import ImageSlider from './ImageSlider';
import Service from './Service';
import TeamMember from './TeamMember';

export {
	HeaderHome,
	HeaderStandard,
	ImageSlider,
	Service,
	TeamMember,
};

export const components = {
	header_home: HeaderHome,
	header_standard: HeaderStandard,
	image_slider: ImageSlider,
	service: Service,
	team_member: TeamMember,
};
