// This file is generated by Slice Machine. Update with care!

import HeaderHome from './HeaderHome';
import HeaderStandard from './HeaderStandard';
import ImgCarousel from './ImgCarousel';
import OurFramework from './OurFramework';
import Quote from './Quote';
import TeamMember from './TeamMember';
import VerticalListSmall from './VerticalListSmall';

export {
	HeaderHome,
	HeaderStandard,
	ImgCarousel,
	OurFramework,
	Quote,
	TeamMember,
	VerticalListSmall,
};

export const components = {
	header_home: HeaderHome,
	header_standard: HeaderStandard,
	img_carousel: ImgCarousel,
	our_framework: OurFramework,
	quote: Quote,
	team_member: TeamMember,
	vertical_list_small: VerticalListSmall,
};
